"""initial

Revision ID: 3d917627d61b
Revises: ee08510e2659
Create Date: 2025-02-05 19:23:53.979553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d917627d61b'
down_revision: Union[str, None] = 'ee08510e2659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('username', sa.String(), nullable=False))
    op.add_column('tasks', sa.Column('status', sa.String(), nullable=False))
    op.add_column('tasks', sa.Column('date', sa.DateTime(), nullable=False))
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'tasks', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='unique')
    op.alter_column('tasks', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('tasks', 'date')
    op.drop_column('tasks', 'status')
    op.drop_column('tasks', 'username')
    # ### end Alembic commands ###
