"""initial

Revision ID: 073df8e92402
Revises: 59c7ba5add90
Create Date: 2025-02-06 15:39:05.917390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '073df8e92402'
down_revision: Union[str, None] = '59c7ba5add90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('creator', sa.String(), nullable=False))
    op.drop_constraint('tasks_username_key', 'tasks', type_='unique')
    op.drop_column('tasks', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('tasks_username_key', 'tasks', ['username'])
    op.drop_column('tasks', 'creator')
    # ### end Alembic commands ###
