"""initial

Revision ID: db8b64f9f4e8
Revises: 073df8e92402
Create Date: 2025-02-06 16:08:27.929206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db8b64f9f4e8'
down_revision: Union[str, None] = '073df8e92402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('creator_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['creator_id'], ['id'], ondelete='SET NULL')
    op.drop_column('tasks', 'creator')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('creator', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'creator_id')
    # ### end Alembic commands ###
