"""initial

Revision ID: 0da8b977b852
Revises: db8b64f9f4e8
Create Date: 2025-02-25 09:00:16.301065

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0da8b977b852"
down_revision: Union[str, None] = "db8b64f9f4e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("tasks_creator_id_fkey", "tasks", type_="foreignkey")
    op.create_foreign_key(
        None, "tasks", "users", ["creator_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.create_foreign_key(
        "tasks_creator_id_fkey",
        "tasks",
        "users",
        ["creator_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
